### ISSUE TITLE
Trouble decoding from group service JSON response

### ISSUE THREAD

**Issue by saffa19** [nicomazz/benza#13]
- According to the terminal output below, there is no data that you can call .length() on in the polyline-encoded path.
- On the plus side, `id` and `name` both work just fine (printed out with print() in the output down below)
```
Performing hot restart...                                        
Restarted application in 12,599ms.
I/flutter ( 4392): ______________________________________________ tab index = 1 ______________________________________________
I/flutter ( 4392): Instance of 'Future<Group>'
I/flutter ( 4392): this is the id: 10
I/flutter ( 4392): this is the name: Aberdeen
I/flutter ( 4392): this is the startloc: null
I/flutter ( 4392): this is the endloc: null
E/flutter ( 4392): [ERROR:flutter/shell/common/shell.cc(186)] Dart Error: Unhandled exception:
E/flutter ( 4392): NoSuchMethodError: The getter 'length' was called on null.
E/flutter ( 4392): Receiver: null
E/flutter ( 4392): Tried calling: length
E/flutter ( 4392): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter ( 4392): #1      decodePolyline (package:benza/models/Group.dart:43:32)
E/flutter ( 4392): #2      new Group.fromJson (package:benza/models/Group.dart:21:29)
E/flutter ( 4392): #3      GroupDataProvider.fetchGroup (package:benza/resources/group_provider.dart:21:20)
E/flutter ( 4392): <asynchronous suspension>
E/flutter ( 4392): #4      GroupList._getData (package:benza/pages/groups/group_list_page.dart:49:35)
E/flutter ( 4392): <asynchronous suspension>
E/flutter ( 4392): #5      GroupList.build (package:benza/pages/groups/group_list_page.dart:14:15)
```
- Also, when I comment out the path, it can retrieve the name of the first user in the group but doesn't like the way it's  formatted, so breaks instead of skipping the list of `users` in the group.
- I think it's all down to questionable JSON decoding and also the initial datatypes of the attrs in a Group object. (below is what the `path` that we give to the db looks like... very messy)
```
[LatLng(latitude:-53.35644, longitude:82.040101), LatLng(latitude:-53.358807, longitude:81.992644),
```
Files of interest:
- the structure of a Group object and how its `path` is supposed to be decoded is in [Group.dart](https://github.com/nicomazz/benza/blob/master/benzaApp/lib/models/Group.dart).
- fetchGroup() in [group_provider.dart](https://github.com/nicomazz/benza/blob/master/benzaApp/lib/resources/group_provider.dart) sends the http request to the groups web service.
- _getData() in [group_list_page.dart](https://github.com/nicomazz/benza/blob/master/benzaApp/lib/pages/group_list_page.dart) is where the call to fetchGroup() is made.

**Comment by saffa19** [comment]
I've made decent progress with this. Have altered the structure of a group object as it's stored in the db by the Flask API and it seems to have resolved quite a few issues.
I've sacrificed quite a lot of functionality though, so will start building the complexity back up again.

**Comment by saffa19** [comment]
Semi-fixed! Groups can be created in-app from create_group_page.dart.
These groups are stored in the mysql db (in the active Docker container) and can be retrieved in group_list_page.dart.

Now to store lists of users in the db instead of just one..
