### ISSUE TITLE
Can't use TextField in create_group_page.dart

### ISSUE THREAD

**Issue by saffa19** [nicomazz/benza#9]
Tapping on a text field in the Create New Group page results in bad things happening (screenshot below).

First part of the error output:
```
I/flutter ( 6025): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═════════════════════════════════════════════════
I/flutter ( 6025): The following NoSuchMethodError was thrown building MyMap(dirty, state: MyMapState#3a039):
I/flutter ( 6025): The method '[]' was called on null.
I/flutter ( 6025): Receiver: null
I/flutter ( 6025): Tried calling: [](0)
I/flutter ( 6025): 
I/flutter ( 6025): When the exception was thrown, this was the stack:
I/flutter ( 6025): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter ( 6025): #1      MyMapState.build (package:benza/services/map_utilities.dart:33:32)
I/flutter ( 6025): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
```
![flutter_01](https://user-images.githubusercontent.com/31897351/52960789-6e945480-3391-11e9-81fb-4997c35d0086.png)

**Comment by saffa19** [comment]
Think it's because it's still trying to use the old maps workaround.
No maps generated using the old method so it's breaking when it tries to find them?
